### ISSUE TITLE
You could upgrade the double cash to 36

### ISSUE THREAD

**Issue by ChocotoneSaDD** [MaliciousFiles/BTD6-Modding#3]
You could upgrade the double cash to 36

**Comment by emkexy** [comment]
yeah, we need update

**Comment by MaliciousFiles** [comment]
Hello, and thank you for reaching out. I've made a newer and more expansive version at [https://github.com/MaliciousFiles/EditPlayerData](https://github.com/MaliciousFiles/EditPlayerData). Happy popping!
